#!/usr/bin/env bash
# One-command local IAMS environment on Linux: SQL Server in a podman container,
# databases bootstrapped from the EF models, API+Web running, admin user created.
#
#   ./scripts/local-db.sh up        # container + DBs + api/web + admin user (idempotent)
#   ./scripts/local-db.sh stop      # stop apps and the container (data volume kept)
#   ./scripts/local-db.sh status
#   ./scripts/local-db.sh destroy   # remove the container AND the data volume
#
# Generated settings land in scripts/local.env (gitignored). Existing secrets in
# local.env (JwtSettings__Secret, ApiSettings__ApiKey, MSSQL_SA_PASSWORD) are reused.
#
# Login after "up": http://localhost:5273  —  admin@local.test / LocalAdmin1
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
envfile="$repo/scripts/local.env"

CONTAINER=iams-mssql
VOLUME=iams-mssql-data
IMAGE=mcr.microsoft.com/mssql/server:2022-latest
API_URL_DEFAULT=http://localhost:5175
WEB_URL_DEFAULT=http://localhost:5273
ADMIN_EMAIL=admin@local.test
ADMIN_PASSWORD=LocalAdmin1

# --- helpers -----------------------------------------------------------------

env_get() { # env_get VAR — read a VAR="value" line from local.env, if present
  [ -f "$envfile" ] || return 0
  sed -n "s/^$1=\"\\(.*\\)\"$/\\1/p" "$envfile" | tail -1
}

# openssl's finite output avoids the pipefail/SIGPIPE trap of tr </dev/urandom | head
gen_secret() { openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | head -c "$1"; }

# -I: QUOTED_IDENTIFIER ON, required for tables with filtered indexes
sql() { podman exec "$CONTAINER" /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -C -b -I -Q "$1"; }

wait_for() { # wait_for "label" timeout_s command...
  local label="$1" timeout="$2"; shift 2
  local waited=0
  until "$@" >/dev/null 2>&1; do
    sleep 3; waited=$((waited + 3))
    if [ "$waited" -ge "$timeout" ]; then
      echo "ERROR: timed out waiting for $label" >&2; return 1
    fi
  done
  echo "    $label ready (${waited}s)"
}

conn() { echo "Server=localhost,1433;Database=$1;User Id=sa;Password=$SA_PASSWORD;TrustServerCertificate=True"; }

# --- commands ----------------------------------------------------------------

cmd_up() {
  command -v podman >/dev/null || { echo "podman is required" >&2; exit 1; }

  # Reuse secrets from an existing local.env; generate what is missing.
  SA_PASSWORD="$(env_get MSSQL_SA_PASSWORD)"; [ -n "$SA_PASSWORD" ] || SA_PASSWORD="Sa1$(gen_secret 21)"
  API_KEY="$(env_get ApiSettings__ApiKey)";   [ -n "$API_KEY" ]     || API_KEY="local-$(gen_secret 32)"
  JWT_SECRET="$(env_get JwtSettings__Secret)"; [ -n "$JWT_SECRET" ] || JWT_SECRET="$(gen_secret 48)"

  echo "==> SQL Server container ($CONTAINER)"
  if ! podman container exists "$CONTAINER"; then
    podman run -d --name "$CONTAINER" \
      -e ACCEPT_EULA=Y -e MSSQL_SA_PASSWORD="$SA_PASSWORD" -e MSSQL_PID=Developer \
      -p 1433:1433 -v "$VOLUME":/var/opt/mssql \
      "$IMAGE" >/dev/null
  elif [ "$(podman inspect -f '{{.State.Running}}' "$CONTAINER")" != "true" ]; then
    podman start "$CONTAINER" >/dev/null
  fi
  wait_for "SQL Server" 120 sql "SELECT 1"

  echo "==> Writing $envfile"
  cat > "$envfile" <<EOF
# Generated by scripts/local-db.sh — local podman SQL Server environment.
# Regenerate any time with: ./scripts/local-db.sh up
ConnectionStrings__MasterConnection="$(conn TenantDb)"
ConnectionStrings__DefaultConnection="$(conn DefaultAgencyDb)"
ConnectionStrings__IntegrationConnection="$(conn IntegrationDb)"
ApiSettings__ApiKey="$API_KEY"
JwtSettings__Secret="$JWT_SECRET"
MSSQL_SA_PASSWORD="$SA_PASSWORD"
LocalBootstrap="true"
MasterDb__AutoMigrate="true"
API_URL="$API_URL_DEFAULT"
WEB_URL="$WEB_URL_DEFAULT"
ADMIN_URL="http://localhost:2554"
TENANT="default"
EOF

  echo "==> Starting API (bootstraps databases on first run)"
  "$repo/scripts/run-local.sh" stop api web >/dev/null 2>&1 || true
  "$repo/scripts/run-local.sh" start api
  wait_for "API" 120 curl -sf "$API_URL_DEFAULT/swagger/v1/swagger.json" -o /dev/null

  echo "==> Pointing the 'default' tenant at the local database"
  sql "UPDATE [TenantDb].dbo.Tenants SET ConnectionString = '$(conn DefaultAgencyDb)' WHERE Identifier = 'default';"

  echo "==> Starting Web (seeds roles and permissions)"
  "$repo/scripts/run-local.sh" start web
  wait_for "Web" 120 curl -sf "$WEB_URL_DEFAULT/login" -o /dev/null

  echo "==> Ensuring admin user ($ADMIN_EMAIL)"
  register_response=$(curl -s -X POST "$API_URL_DEFAULT/api/auth/register" \
    -H "X-API-Key: $API_KEY" -H "X-Tenant-ID: default" -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\",\"firstName\":\"Local\",\"lastName\":\"Admin\",\"roleName\":\"Admin\"}")
  case "$register_response" in
    *successfully*)     echo "    admin user created" ;;
    *already\ exists*)  echo "    admin user already exists" ;;
    *)                  echo "    unexpected register response: $register_response" >&2 ;;
  esac

  # Countries are not part of the EF seed data (SeedCountries is disabled in the code;
  # production fills the table via the external DAS sync, which is not reachable from
  # dev machines). Seed a minimal set directly so the uyruk dropdown works — KKTC (601)
  # first, matching the country-code rule used by the customer form.
  echo "==> Seeding countries (KKTC + common)"
  sql "USE DefaultAgencyDb;
IF NOT EXISTS (SELECT 1 FROM dbo.Countries WHERE Code = '601')
INSERT INTO dbo.Countries (Code, NameTr, NameEn, PhoneCode, IsActive, DisplayOrder, CreatedOn, CreatedBy, IsDeleted) VALUES
 ('601', N'Kuzey Kıbrıs Türk Cumhuriyeti', N'Turkish Republic of Northern Cyprus', '+392', 1, 1, GETUTCDATE(), 'local-db.sh', 0),
 ('052', N'Türkiye', N'Turkey', '+90', 1, 2, GETUTCDATE(), 'local-db.sh', 0),
 ('044', N'Birleşik Krallık', N'United Kingdom', '+44', 1, 3, GETUTCDATE(), 'local-db.sh', 0),
 ('001', N'Amerika Birleşik Devletleri', N'United States', '+1', 1, 4, GETUTCDATE(), 'local-db.sh', 0),
 ('030', N'Yunanistan', N'Greece', '+30', 1, 5, GETUTCDATE(), 'local-db.sh', 0);"

  # Smoke-check that login works end to end.
  login_status=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$API_URL_DEFAULT/api/auth/login" \
    -H "X-API-Key: $API_KEY" -H "X-Tenant-ID: default" -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}")
  [ "$login_status" = "200" ] && echo "    login verified (API)" || echo "    WARNING: login check returned HTTP $login_status" >&2

  echo
  echo "Done. Open $WEB_URL_DEFAULT and log in as $ADMIN_EMAIL / $ADMIN_PASSWORD"
}

cmd_stop() {
  "$repo/scripts/run-local.sh" stop || true
  podman container exists "$CONTAINER" && podman stop "$CONTAINER" >/dev/null && echo "container stopped (data kept)"
}

cmd_status() {
  "$repo/scripts/run-local.sh" status || true
  if podman container exists "$CONTAINER"; then
    echo "mssql: $(podman inspect -f '{{.State.Status}}' "$CONTAINER") (container $CONTAINER, volume $VOLUME)"
  else
    echo "mssql: no container"
  fi
}

cmd_destroy() {
  cmd_stop || true
  podman rm -f "$CONTAINER" >/dev/null 2>&1 || true
  podman volume rm "$VOLUME" >/dev/null 2>&1 || true
  echo "container and data volume removed"
}

case "${1:-up}" in
  up)      cmd_up ;;
  stop)    cmd_stop ;;
  status)  cmd_status ;;
  destroy) cmd_destroy ;;
  *) echo "usage: $0 {up|stop|status|destroy}" >&2; exit 1 ;;
esac
