<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IAMS.Admin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
    <PackageReference Include="MudBlazor" Version="8.9.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IAMS.Application\IAMS.Application.csproj" />
    <ProjectReference Include="..\IAMS.Identity\IAMS.Identity.csproj" />
    <ProjectReference Include="..\IAMS.MultiTenancy\IAMS.MultiTenancy.csproj" />
    <ProjectReference Include="..\IAMS.Persistence\IAMS.Persistence.csproj" />
    <ProjectReference Include="..\IAMS.Shared\IAMS.Shared.csproj" />
  </ItemGroup>

</Project>
